{-# OPTIONS -fno-warn-incomplete-patterns #-}
module Printmatal where

-- pretty-printer generated by the BNF converter

import Absmatal
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))
  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])



instance Print Program where
  prt i e = case e of
   Progr external_declarations -> prPrec i 0 (concatD [prt 0 external_declarations])


instance Print External_declaration where
  prt i e = case e of
   Afunc function_def -> prPrec i 0 (concatD [prt 0 function_def])
   Global dec -> prPrec i 0 (concatD [prt 0 dec])
   StructDec struct_spec -> prPrec i 0 (concatD [prt 0 struct_spec])

  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Declarator where
  prt i e = case e of
   DVariable type_specifier id -> prPrec i 0 (concatD [prt 0 type_specifier , prt 0 id])


instance Print Dec where
  prt i e = case e of
   Declaration declarator -> prPrec i 0 (concatD [prt 0 declarator , doc (showString ";")])

  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Type_specifier where
  prt i e = case e of
   TVoid  -> prPrec i 0 (concatD [doc (showString "void")])
   TInt  -> prPrec i 0 (concatD [doc (showString "int")])
   TBool  -> prPrec i 0 (concatD [doc (showString "bool")])
   TStruct id -> prPrec i 0 (concatD [prt 0 id])
   TArray type_specifier -> prPrec i 0 (concatD [prt 0 type_specifier , doc (showString "[]")])
   TMap type_specifier0 type_specifier -> prPrec i 0 (concatD [prt 0 type_specifier0 , doc (showString "<<") , prt 0 type_specifier , doc (showString ">>")])


instance Print Struct_spec where
  prt i e = case e of
   Struct id decs -> prPrec i 0 (concatD [doc (showString "struct") , prt 0 id , doc (showString "{") , prt 0 decs , doc (showString "}")])


instance Print Function_def where
  prt i e = case e of
   FuncNoParams declarator compound_stmt -> prPrec i 0 (concatD [prt 0 declarator , doc (showString "(") , doc (showString ")") , prt 0 compound_stmt])
   FuncParams declarator parameter_declarations compound_stmt -> prPrec i 0 (concatD [prt 0 declarator , doc (showString "(") , prt 0 parameter_declarations , doc (showString ")") , prt 0 compound_stmt])


instance Print Parameter_declarations where
  prt i e = case e of
   ParamDec declarator -> prPrec i 0 (concatD [prt 0 declarator])
   MoreParamDec parameter_declarations declarator -> prPrec i 0 (concatD [prt 0 parameter_declarations , doc (showString ",") , prt 0 declarator])


instance Print Stmt where
  prt i e = case e of
   SComp compound_stmt -> prPrec i 0 (concatD [prt 0 compound_stmt])
   SExpr expression_stmt -> prPrec i 0 (concatD [prt 0 expression_stmt])
   SSel selection_stmt -> prPrec i 0 (concatD [prt 0 selection_stmt])
   SIter iter_stmt -> prPrec i 0 (concatD [prt 0 iter_stmt])
   SJump jump_stmt -> prPrec i 0 (concatD [prt 0 jump_stmt])
   SPrint print_stmt -> prPrec i 0 (concatD [prt 0 print_stmt])
   SInit init_stmt -> prPrec i 0 (concatD [prt 0 init_stmt])

  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Compound_Stmt where
  prt i e = case e of
   SCompOne  -> prPrec i 0 (concatD [doc (showString "{") , doc (showString "}")])
   SCompTwo stmts -> prPrec i 0 (concatD [doc (showString "{") , prt 0 stmts , doc (showString "}")])
   SCompThree decs stmts -> prPrec i 0 (concatD [doc (showString "{") , prt 0 decs , prt 0 stmts , doc (showString "}")])


instance Print Expression_Stmt where
  prt i e = case e of
   SExprOne  -> prPrec i 0 (concatD [doc (showString ";")])
   SExprTwo exp -> prPrec i 0 (concatD [prt 0 exp , doc (showString ";")])


instance Print Selection_Stmt where
  prt i e = case e of
   SSelOne exp stmt -> prPrec i 0 (concatD [doc (showString "if") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 stmt])
   SSelTwo exp stmt0 stmt -> prPrec i 0 (concatD [doc (showString "if") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 stmt0 , doc (showString "else") , prt 0 stmt])


instance Print Iter_Stmt where
  prt i e = case e of
   SIterOne exp stmt -> prPrec i 0 (concatD [doc (showString "while") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 stmt])
   SIterTwo expression_stmt0 expression_stmt stmt -> prPrec i 0 (concatD [doc (showString "for") , doc (showString "(") , prt 0 expression_stmt0 , prt 0 expression_stmt , doc (showString ")") , prt 0 stmt])
   SIterThree expression_stmt0 expression_stmt exp stmt -> prPrec i 0 (concatD [doc (showString "for") , doc (showString "(") , prt 0 expression_stmt0 , prt 0 expression_stmt , prt 0 exp , doc (showString ")") , prt 0 stmt])


instance Print Jump_Stmt where
  prt i e = case e of
   SJumpOne exp -> prPrec i 0 (concatD [doc (showString "return") , prt 0 exp , doc (showString ";")])


instance Print Print_Stmt where
  prt i e = case e of
   SPrintOne exp -> prPrec i 0 (concatD [doc (showString "print") , prt 0 exp , doc (showString ";")])


instance Print Init_Stmt where
  prt i e = case e of
   SInitOne id exp -> prPrec i 0 (concatD [doc (showString "init") , prt 0 id , doc (showString "[") , prt 0 exp , doc (showString "]") , doc (showString ";")])


instance Print Exp where
  prt i e = case e of
   EComma exp0 exp -> prPrec i 0 (concatD [prt 0 exp0 , doc (showString ",") , prt 1 exp])
   EAssign exp0 assignment_op exp -> prPrec i 1 (concatD [prt 4 exp0 , prt 0 assignment_op , prt 1 exp])
   EEq exp0 exp -> prPrec i 2 (concatD [prt 2 exp0 , doc (showString "==") , prt 3 exp])
   ENeq exp0 exp -> prPrec i 2 (concatD [prt 2 exp0 , doc (showString "!=") , prt 3 exp])
   ELthen exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString "<") , prt 4 exp])
   EGrthen exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString ">") , prt 4 exp])
   ELe exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString "<=") , prt 4 exp])
   EGe exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString ">=") , prt 4 exp])
   EPlus exp0 exp -> prPrec i 4 (concatD [prt 4 exp0 , doc (showString "+") , prt 3 exp])
   EMinus exp0 exp -> prPrec i 4 (concatD [prt 4 exp0 , doc (showString "-") , prt 3 exp])
   ETimes exp0 exp -> prPrec i 5 (concatD [prt 5 exp0 , doc (showString "*") , prt 4 exp])
   EDiv exp0 exp -> prPrec i 5 (concatD [prt 5 exp0 , doc (showString "/") , prt 4 exp])
   ESelect exp id -> prPrec i 6 (concatD [prt 6 exp , doc (showString ".") , prt 0 id])
   EArray exp0 exp -> prPrec i 6 (concatD [prt 6 exp0 , doc (showString "[") , prt 0 exp , doc (showString "]")])
   EFunk exp -> prPrec i 6 (concatD [prt 6 exp , doc (showString "(") , doc (showString ")")])
   EFunkPar exp exps -> prPrec i 6 (concatD [prt 6 exp , doc (showString "(") , prt 1 exps , doc (showString ")")])
   EMap exp0 exp -> prPrec i 6 (concatD [prt 6 exp0 , doc (showString "<<") , prt 0 exp , doc (showString ">>")])
   EPostInc exp -> prPrec i 7 (concatD [prt 7 exp , doc (showString "++")])
   EPostDec exp -> prPrec i 7 (concatD [prt 7 exp , doc (showString "--")])
   EVar id -> prPrec i 8 (concatD [prt 0 id])
   EConst constant -> prPrec i 8 (concatD [prt 0 constant])

  prtList es = case es of
   [x] -> (concatD [prt 1 x])
   x:xs -> (concatD [prt 1 x , doc (showString ",") , prt 1 xs])

instance Print Constant where
  prt i e = case e of
   EInt n -> prPrec i 0 (concatD [prt 0 n])
   ETrue  -> prPrec i 0 (concatD [doc (showString "true")])
   EFalse  -> prPrec i 0 (concatD [doc (showString "false")])


instance Print Assignment_op where
  prt i e = case e of
   Assign  -> prPrec i 0 (concatD [doc (showString "=")])
   AssignMul  -> prPrec i 0 (concatD [doc (showString "*=")])
   AssignDiv  -> prPrec i 0 (concatD [doc (showString "/=")])
   AssignAdd  -> prPrec i 0 (concatD [doc (showString "+=")])
   AssignSub  -> prPrec i 0 (concatD [doc (showString "-=")])



